// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef helper_window_hpp
#define helper_window_hpp
#include <FL/Fl.H>
void set_network_draw(int val);
#include <FL/Fl_Double_Window.H>
extern fltkview *sim_win;
#include <FL/Fl_Slider.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Choice.H>
extern Fl_Menu_Item menu_Roads[];
#endif
